### ISSUE TITLE
Find ancestor git root?

### ISSUE THREAD

**Issue by gdean123** [ericTsiliacos/portal#3]
Hello!

My pair and I have been working in a nested directory a lot. Would it be possible for portal to support searching up the directory hierarchy until it finds the closest git root?

We have been hitting the "current working directory must be root of git project" error a lot, which has been painful.

Cheers! =)

**Comment by ericTsiliacos** [comment]
thanks for the feedback @gdean123! I'll add this to the backlog. I can probably get this done by today, if not by this weekend.

**Comment by ericTsiliacos** [comment]
@gdean123, just released v3.1.0 which describes your desired behavior (if I understood it correctly). Before I close out this issue, would you give it a try (`brew uninstall portal && brew install portal`) and let know if it satisfies your use case? thanks!

**Comment by gdean123** [comment]
It works like a charm! Thank you so much!

**Comment by ericTsiliacos** [comment]
@gdean123, just noticed an issue that you'll likely face if you are in the process of adding new files. If you have an untracked filed from say the root of our project but try to run `portal push` from a different directory, it'll ignore the untracked file because currently `portal push` uses `git add .` which is only aware of tracked files in the current directory. The fix is to use `git add --all` instead. I'll let you know when I've published the fix.

**Comment by ericTsiliacos** [comment]
@gdean123, ok, latest version `v3.2.0` should have the fix if you need it. You can install portal to the latest version. Let me know if you run into any further problems.

**Comment by ericTsiliacos** [comment]
Going to close issue as problem has been addressed
