### ISSUE TITLE
Compatible branch naming

### ISSUE THREAD

**Issue by gdean123** [ericTsiliacos/portal#4]
Hello!

My pair is using git duet, and I am using git-together (technically git-author, which is a wrapper). Unfortunately, it looks like I can't `portal pull` what he `portal push`es.

The branch names appear to be:

`portal-ab-gd` for git-together
`tmp/portal/ab-gd` for git-duet

Could those be unified so that we could send changesets back and forth?

Thank you!

**Comment by ericTsiliacos** [comment]
hi @gdean123! This was my mistake. I recently made a new release and forgot to specify it as a breaking change by bumping the MAJOR version number. Normally, the tool checks to see if both users are on the same MAJOR version and prevents the mixup. So likely, what's happening is you have an older version of portal and your pair has the new version that puts the temporary branches at `/tmp/portal/<PAIR>`. The easiest fix right now is for both of you are using the exact same version of portal. 

 I'll go, a head a make another MAJOR release so that in the future this won't happen again. Apologies!

**Comment by gdean123** [comment]
My pair just installed it today, so he would have had whatever was the latest at the beginning of the day today. I expect that was 3.0.0.

I'm not 100% sure which version I had. I just ran the uninstall, but it printed out that it was removing version 64 (homebrew's version). I'm not sure how to get from that to the portal version. Maybe you know how?

```
$ brew uninstall portal && brew install portal && portal --version
Uninstalling /usr/local/Cellar/portal/64... (3 files, 4.1MB)
```

**Comment by ericTsiliacos** [comment]
oh! hmm, I'm not sure either. I think for now, we'll close this issue. If you experience this issue in the future, don't hesitate to re-open the issue. Let's include the version numbers of portal of you and your pair the next time you see the issue. Hopefully you are able to use `portal` again just fine now, cheers!
